version: '3.3'

services:
  web:
    image: itzg/rcon
    ports:
      - 4326:4326
      - 4327:4327
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: 1.13.2